@startuml usecase

actor Admin as "Pengelola (Admin)"
actor Customer as "Pelanggan"

rectangle "Aplikasi Manajemen Menu Restoran Mie Gacoan" {
  
  usecase "Kelola Menu" as UC1
  usecase "Kelola Pesanan" as UC2
  usecase "Proses Pembayaran" as UC3
  usecase "Lihat Menu" as UC4
  usecase "Pesan Makanan" as UC5
  
}

Admin -- UC1 : Mengelola menu
Admin -- UC2 : Mencatat pesanan
Admin -- UC3 : Memproses pembayaran
Customer -- UC4 : Melihat menu
Customer -- UC5 : Memesan makanan

@enduml
