@startuml academic 

actor Mahasiswa as mhs
actor Dosen as dsn

package ClassRoom {
    usecase "pilih mata kuliah" as U1
    usecase "jadwal kuliah" as U2
    usecase "Ruang Perkuliahan" as U3
    usecase "menerima penjadwalan perkuliahan" as U4
    usecase "mengajar" as U7
    usecase "terima mengajar" as U5
    usecase "tolak mengajar" as U6
}

mhs -->U1
U1 -->U2 :include
U1 -->U3 :include
mhs --> U4
dsn --> U7
U7 --> U6 : extend
U7 --> U5 : extend

@enduml